### ISSUE TITLE
crash on multiplayer game map size 8 latest beta release of serflings

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#33]
mostly MP game is very stable, but now i am getting quite often CTO with this message on host:

Windows 10 10.0 (x86) // but its actually 64bit win10???
Java 1.8.0_144 (Oracle Corporation)
java.lang.ArrayIndexOutOfBoundsException: 65280
	at net.simpleguide.b.a.j.a.b.a(net.simpleguide.Main:1344)
	at net.simpleguide.b.a.k.a.h.a(net.simpleguide.Main:12473)
	at net.simpleguide.b.a.a.a(net.simpleguide.Main:38795)
	at net.simpleguide.b.a.o.d(net.simpleguide.Main:449)
	at net.simpleguide.a.a.a.run(net.simpleguide.Main:1406)
	at java.lang.Thread.run(Unknown Source)

client:

Windows 10 10.0 (amd64) 
Java 1.8.0_261 (Oracle Corporation)
java.lang.ArrayIndexOutOfBoundsException: 65280
	at net.simpleguide.b.a.j.a.b.a(net.simpleguide.Main:1344)
	at net.simpleguide.b.a.k.a.h.a(net.simpleguide.Main:12473)
	at net.simpleguide.b.a.a.a(net.simpleguide.Main:38795)
	at net.simpleguide.b.a.o.d(net.simpleguide.Main:449)
	at net.simpleguide.a.a.a.run(net.simpleguide.Main:1406)
	at java.lang.Thread.run(Unknown Source)

[SAVE6.zip](https://github.com/nicymike/serflings/files/5367170/SAVE6.zip)

**Comment by nicymike** [comment]
Are you using a 32bit Java runtime? This could explain the x86 on Windows 10.

The crash occurs because of one of the watch towers of the red player which is currently beeing built and has way too much planks. I don't know why there are so many planks but if you burn it down the crash will not happen.

I will try to find the reason for this.

**Comment by nicymike** [comment]
I fixed the savegame for now: [SAVE6.ZIP](https://github.com/nicymike/serflings/files/5380880/SAVE6.ZIP)

There might be a bug at delivering somewhere.

**Comment by Wakeboardtiger** [comment]
Awesome, thanks a lot.

**Comment by nicymike** [comment]
I fixed the crash in the next development version. I will fix the reason for the unneeded planks lather when I rewrite the logic for stocks and delivering.
