### ISSUE TITLE
No sound in application in Manjaro Linux for raspberry pi

### ISSUE THREAD

**Issue by ws1968** [nicymike/serflings#57]
I have no sound with serflings.
I'm using Manjaro Linux 64bit for the raspberry pi (aarch64) with java8 from oracle 
(Java(TM) SE Runtime Environment (build 1.8.0_281-b09))
It works fine if I use raspberry pi os (32 bit with java8 from oracle)

I get the following error when running java -jar serflings-1.0.0-SNAPSHOT.jar :+1: 

javax.sound.midi.MidiUnavailableException: Can not open line
	at com.sun.media.sound.SoftSynthesizer.open(SoftSynthesizer.java:1155)
	at com.sun.media.sound.SoftSynthesizer.open(SoftSynthesizer.java:1066)
	at a.a.h.<init>(net.simpleguide.Main:2169)
	at a.a.f.a(net.simpleguide.Main:1230)
	at a.a.l.a(net.simpleguide.Main:3524)
	at a.a.c.run(net.simpleguide.Main:96)
Caused by: java.lang.IllegalArgumentException: No line matching interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian is supported.
	at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:479)
	at javax.sound.sampled.AudioSystem.getSourceDataLine(AudioSystem.java:606)
	at com.sun.media.sound.SoftSynthesizer.open(SoftSynthesizer.java:1095)
	... 5 more
javax.sound.midi.MidiUnavailableException: Can not open line
	at com.sun.media.sound.SoftSynthesizer.open(SoftSynthesizer.java:1155)
	at com.sun.media.sound.SoftSynthesizer.open(SoftSynthesizer.java:1066)
	at a.a.h.c(net.simpleguide.Main:1272)
	at a.a.h.<init>(net.simpleguide.Main:2183)
	at a.a.f.a(net.simpleguide.Main:1230)
	at a.a.l.a(net.simpleguide.Main:3524)
	at a.a.c.run(net.simpleguide.Main:96)

**Comment by nicymike** [comment]
Thank you for trying the game on a Raspberry Pi. I don't have this device but I try to help you out with this.

1. Does "no sound" mean both no music and no sound effects?
2. Can you please test with Version 0.26.0 and post a screenshot with dev info (press F3 ingame)?
3. Please also post a screenshot of Version 1.0.0-SNAPSHOT with dev info.

**Comment by ws1968** [comment]
I have no sound and no music.
both versions (0.26 and 1.0) have the same problem.

If I use the 32bit raspberry pi os with oracle java 8 then music and sound work ok.

![serflings-0 26](https://user-images.githubusercontent.com/81056738/116162133-8e3f0a00-a6cb-11eb-971f-b3e090e0e639.png)
![serflings-1 0 0](https://user-images.githubusercontent.com/81056738/116162142-91d29100-a6cb-11eb-8d65-990b140a2a85.png)

**Comment by ws1968** [comment]
after searching the whole day for a solution I found it. The problem was with the java release from oracle. I downloaded a newer version (I had .281b10 and now .291b10) I have sound and music!

**Comment by nicymike** [comment]
Very nice, so it was a problem with Java VM.

You may close this issue if it is solved.
